up

diff --git a/minitage.patch b/minitage.patch
--- a/minitage.patch
+++ b/minitage.patch
@@ -1,6 +1,6 @@
-diff -ur cyrus-sasl-2.1.24/aclocal.m4 cyrus-sasl-2.1.24.new/aclocal.m4
+diff -Nur cyrus-sasl-2.1.24/aclocal.m4 cyrus-sasl-2.1.24.new//aclocal.m4
 --- cyrus-sasl-2.1.24/aclocal.m4	2009-08-13 19:49:38.000000000 +0200
-+++ cyrus-sasl-2.1.24.new/aclocal.m4	2010-04-05 18:43:16.000000000 +0200
++++ cyrus-sasl-2.1.24.new//aclocal.m4	2011-10-16 23:50:00.633507763 +0200
 @@ -1741,7 +1741,7 @@
  	fi
  
@@ -10,9 +10,9 @@ diff -ur cyrus-sasl-2.1.24/aclocal.m4 cyrus-sasl-2.1.24.new/aclocal.m4
            do
  	    LIBS="$saved_LIBS -l$dbname"
  	    AC_TRY_LINK([#include <stdio.h>
-diff -ur cyrus-sasl-2.1.24/cmulocal/berkdb.m4 cyrus-sasl-2.1.24.new/cmulocal/berkdb.m4
+diff -Nur cyrus-sasl-2.1.24/cmulocal/berkdb.m4 cyrus-sasl-2.1.24.new//cmulocal/berkdb.m4
 --- cyrus-sasl-2.1.24/cmulocal/berkdb.m4	2009-05-07 17:21:14.000000000 +0200
-+++ cyrus-sasl-2.1.24.new/cmulocal/berkdb.m4	2010-04-05 18:43:16.000000000 +0200
++++ cyrus-sasl-2.1.24.new//cmulocal/berkdb.m4	2011-10-16 23:50:00.633507763 +0200
 @@ -213,7 +213,7 @@
  	fi
  
@@ -22,9 +22,9 @@ diff -ur cyrus-sasl-2.1.24/cmulocal/berkdb.m4 cyrus-sasl-2.1.24.new/cmulocal/ber
            do
  	    LIBS="$saved_LIBS -l$dbname"
  	    AC_TRY_LINK([#include <stdio.h>
-diff -ur cyrus-sasl-2.1.24/configure cyrus-sasl-2.1.24.new/configure
+diff -Nur cyrus-sasl-2.1.24/configure cyrus-sasl-2.1.24.new//configure
 --- cyrus-sasl-2.1.24/configure	2009-08-13 19:50:03.000000000 +0200
-+++ cyrus-sasl-2.1.24.new/configure	2010-04-05 18:43:16.000000000 +0200
++++ cyrus-sasl-2.1.24.new//configure	2011-10-16 23:50:00.641507762 +0200
 @@ -5148,7 +5148,7 @@
  	fi
  
@@ -43,9 +43,9 @@ diff -ur cyrus-sasl-2.1.24/configure cyrus-sasl-2.1.24.new/configure
            do
  	    LIBS="$saved_LIBS -l$dbname"
  	    cat >conftest.$ac_ext <<_ACEOF
-diff -ur cyrus-sasl-2.1.24/saslauthd/aclocal.m4 cyrus-sasl-2.1.24.new/saslauthd/aclocal.m4
+diff -Nur cyrus-sasl-2.1.24/saslauthd/aclocal.m4 cyrus-sasl-2.1.24.new//saslauthd/aclocal.m4
 --- cyrus-sasl-2.1.24/saslauthd/aclocal.m4	2009-08-13 19:50:31.000000000 +0200
-+++ cyrus-sasl-2.1.24.new/saslauthd/aclocal.m4	2010-04-05 18:43:16.000000000 +0200
++++ cyrus-sasl-2.1.24.new//saslauthd/aclocal.m4	2011-10-16 23:50:00.641507762 +0200
 @@ -2068,7 +2068,7 @@
  	fi
  
@@ -55,9 +55,105 @@ diff -ur cyrus-sasl-2.1.24/saslauthd/aclocal.m4 cyrus-sasl-2.1.24.new/saslauthd/
            do
  	    LIBS="$saved_LIBS -l$dbname"
  	    AC_TRY_LINK([#include <stdio.h>
-diff -ur cyrus-sasl-2.1.24/saslauthd/configure cyrus-sasl-2.1.24.new/saslauthd/configure
+diff -Nur cyrus-sasl-2.1.24/saslauthd/configure cyrus-sasl-2.1.24.new//saslauthd/configure
 --- cyrus-sasl-2.1.24/saslauthd/configure	2009-08-13 19:50:49.000000000 +0200
-+++ cyrus-sasl-2.1.24.new/saslauthd/configure	2010-04-05 18:43:16.000000000 +0200
++++ cyrus-sasl-2.1.24.new//saslauthd/configure	2011-10-16 23:50:24.093507490 +0200
+@@ -3639,7 +3639,7 @@
+ if test $ac_cv_func_res_search = yes; then
+   :
+ else
+-  LIBS="-lresolv $LIB_SOCKET $save_LIBS"
++  LIBS="-lresolv -ldb-4.8 $LIB_SOCKET $save_LIBS"
+ 		cat >conftest.$ac_ext <<_ACEOF
+ #line $LINENO "configure"
+ /* confdefs.h.  */
+@@ -3680,7 +3680,7 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  LIB_SOCKET="-lresolv $LIB_SOCKET"
++  LIB_SOCKET="-lresolv -ldb-4.8 $LIB_SOCKET"
+ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+@@ -5689,13 +5689,13 @@
+ 
+   if test "$krb4" != no; then
+ 
+-echo "$as_me:$LINENO: checking for res_search in -lresolv" >&5
+-echo $ECHO_N "checking for res_search in -lresolv... $ECHO_C" >&6
++echo "$as_me:$LINENO: checking for res_search in -lresolv -ldb-4.8" >&5
++echo $ECHO_N "checking for res_search in -lresolv -ldb-4.8... $ECHO_C" >&6
+ if test "${ac_cv_lib_resolv_res_search+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lresolv  $LIBS"
++LIBS="-lresolv -ldb-4.8  $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ #line $LINENO "configure"
+ /* confdefs.h.  */
+@@ -5748,7 +5748,7 @@
+ #define HAVE_LIBRESOLV 1
+ _ACEOF
+ 
+-  LIBS="-lresolv $LIBS"
++  LIBS="-lresolv -ldb-4.8 $LIBS"
+ 
+ fi
+ 
+@@ -6783,13 +6783,13 @@
+   # The choice is reflected in GSSAPIBASE_LIBS
+ 
+ 
+-echo "$as_me:$LINENO: checking for res_search in -lresolv" >&5
+-echo $ECHO_N "checking for res_search in -lresolv... $ECHO_C" >&6
++echo "$as_me:$LINENO: checking for res_search in -lresolv -ldb-4.8" >&5
++echo $ECHO_N "checking for res_search in -lresolv -ldb-4.8... $ECHO_C" >&6
+ if test "${ac_cv_lib_resolv_res_search+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lresolv  $LIBS"
++LIBS="-lresolv -ldb-4.8  $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ #line $LINENO "configure"
+ /* confdefs.h.  */
+@@ -6842,7 +6842,7 @@
+ #define HAVE_LIBRESOLV 1
+ _ACEOF
+ 
+-  LIBS="-lresolv $LIBS"
++  LIBS="-lresolv -ldb-4.8 $LIBS"
+ 
+ fi
+ 
+@@ -7464,13 +7464,13 @@
+ if test "$gssapi" != no; then
+   echo "$as_me:$LINENO: result: with implementation ${gss_impl}" >&5
+ echo "${ECHO_T}with implementation ${gss_impl}" >&6
+-  echo "$as_me:$LINENO: checking for res_search in -lresolv" >&5
+-echo $ECHO_N "checking for res_search in -lresolv... $ECHO_C" >&6
++  echo "$as_me:$LINENO: checking for res_search in -lresolv -ldb-4.8" >&5
++echo $ECHO_N "checking for res_search in -lresolv -ldb-4.8... $ECHO_C" >&6
+ if test "${ac_cv_lib_resolv_res_search+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lresolv  $LIBS"
++LIBS="-lresolv -ldb-4.8  $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ #line $LINENO "configure"
+ /* confdefs.h.  */
+@@ -7519,7 +7519,7 @@
+ echo "$as_me:$LINENO: result: $ac_cv_lib_resolv_res_search" >&5
+ echo "${ECHO_T}$ac_cv_lib_resolv_res_search" >&6
+ if test $ac_cv_lib_resolv_res_search = yes; then
+-  GSSAPIBASE_LIBS="$GSSAPIBASE_LIBS -lresolv"
++  GSSAPIBASE_LIBS="$GSSAPIBASE_LIBS -lresolv -ldb-4.8"
+ fi
+ 
+   SASL_MECHS="$SASL_MECHS libgssapiv2.la"
 @@ -8036,7 +8036,7 @@
  	fi
  
@@ -76,3 +172,29 @@ diff -ur cyrus-sasl-2.1.24/saslauthd/configure cyrus-sasl-2.1.24.new/saslauthd/c
            do
  	    LIBS="$saved_LIBS -l$dbname"
  	    cat >conftest.$ac_ext <<_ACEOF
+@@ -9728,13 +9728,13 @@
+ 
+ 
+ 
+-echo "$as_me:$LINENO: checking for inet_aton in -lresolv" >&5
+-echo $ECHO_N "checking for inet_aton in -lresolv... $ECHO_C" >&6
++echo "$as_me:$LINENO: checking for inet_aton in -lresolv -ldb-4.8" >&5
++echo $ECHO_N "checking for inet_aton in -lresolv -ldb-4.8... $ECHO_C" >&6
+ if test "${ac_cv_lib_resolv_inet_aton+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lresolv  $LIBS"
++LIBS="-lresolv -ldb-4.8  $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ #line $LINENO "configure"
+ /* confdefs.h.  */
+@@ -9787,7 +9787,7 @@
+ #define HAVE_LIBRESOLV 1
+ _ACEOF
+ 
+-  LIBS="-lresolv $LIBS"
++  LIBS="-lresolv -ldb-4.8 $LIBS"
+ 
+ fi
+ 
